name: 'Redmine Sync'
description:
  'Retrieves ticket information from Redmine and updates your issues and pull
  requests'
author: 'Tim Otte'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  redmine-url:
    description: 'The URL of your Redmine instance'
    required: true
  redmine-api-key:
    description: 'The API key for your Redmine instance'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB TOKEN'
    required: true
    default: ${{ github.token }}
  update-title:
    description:
      Should the action update the title of the pull request? `true` or `false`
    default: 'true'
  add-issue-description:
    description:
      Should the body of the pull request be appended with / replaced by the
      issue description? `append` or `replace` or `none`
    default: 'replace'

runs:
  using: node20
  main: dist/index.js
